mahmouddaabas/DA336A-Grupp-Projekt

src/controller/GameLogic.java
src/model/Player.java

Player Klass

---

src/controller/GameLogic.java
src/model/Addition2Numbers.java
src/model/Addition3Numbers.java
src/model/Division2Numbers.java
src/model/MathQuestions.java
src/model/Multiplication2Numbers.java

Updated the internal logic of the MathQuestion superclass and subclasses. Added 2 new subclasses: Addition3Numbers and Division2Numbers. Added test objects for the new classes in GameLogic.

Updated and added MathQuestion subclasses

---

src/model/questions/Addition2Numbers.java
src/model/questions/Addition3Numbers.java
src/model/questions/Division2Numbers.java
src/model/questions/MathQuestions.java
src/model/questions/Subtraction2Numbers.java

Reworked how the answer arrays and fake answers are generated. Reworked the checking of the correct answer. Fixed a mistake in how the fake answers were generated in Division2Numbers.

Updated the MathQuestion classes

---

src/model/HealthPotion.java
src/model/Player.java
src/model/Vendor/Attributes.java
src/model/Vendor/Bag.java
src/model/Vendor/HealthPotion.java
src/model/Vendor/Item.java
src/model/Vendor/VendorNPC.java
src/model/Vendor/Weapon.java

Kommentarer till klasserna: Attributes, Bag, HealthPotion, Item, Weapon och Player. Skapade ett packet Vendor som innehåller allt som handlar om Vendor.

Skrev kommentarer samt skapade packet Vendor

---

src/model/questions/Addition2Numbers.java
src/model/questions/Addition3Numbers.java
src/model/questions/Division2Numbers.java
src/model/questions/MathQuestions.java
src/model/questions/Multiplication2Numbers.java
src/model/questions/Subtraction2Numbers.java
src/model/questions/TestMathQuestions.java

The new generateNewQuestion() method will generate a new question and new answers. This method must be called before any other method is called from the MathQuestion classes.
Also added a TestMathQuestions class that is solely for testing that the MathQuestion classes work as intended.

MathQuestion objects can repeatedly generate questions

---

src/model/questions/Addition2Numbers.java
src/model/questions/Addition3Numbers.java
src/model/questions/Division2Numbers.java
src/model/questions/MathQuestions.java
src/model/questions/Multiplication2Numbers.java
src/model/questions/Subtraction2Numbers.java
src/model/questions/TestMathQuestions.java

Same as MathQuesion-repeated-use but for the new fix

MathQuestion objects can repeatedly generate questions fixed

---

src/view/GameOverScreen.java
src/view/HealthBar.java
src/view/SceneChanger.java

- Health Bar now shows after you enter the first scene.
- Health Bar now correctly removes the hearts in order so it doesn't leave big gaps.

Fixed Health Bar bugs.

---

src/model/questions/Multiplication2Decimals.java
src/model/questions/Subtraction2Decimals.java
src/model/questions/Subtraction2Integers.java
src/model/questions/TestMathQuestions.java

- Subtraction of 2 decimal numbers
- Multiplication of 2 decimal numbers
- Added decimal precision to both numbers in the 2 decimal classes

Added decimal classes

---

src/controller/GameLogic.java
src/controller/LevelCreator.java
src/model/Player.java
src/model/Timer.java
src/view/SceneChanger.java
src/view/SceneCreator.java
src/view/events/Event02.java

1 - Popup menu is now disabled during combat.
2 & 2.1 - New questions generate after death.
3 - Timer now restarts when reaching 0

Bug fixes and added some comments

---

src/model/questions/DivisionFraction2Numbers.java
src/model/questions/MathQuestions.java

Needed for future MathQuestion subclasses.

Small improvement to how MathQuestion handles strings

---

src/controller/GameLogic.java
src/view/events/Event02.java

- Now generates a new question and new answers if the players answer is wrong.
- Changed the way the questions gets shown on the GUI. It is now done in a method in the Controller instead of Event 2.
- Can now easy generate new questions by setting the setOutOfCombat to true and calling generateQuestionAndAnswers.

New question and answers if answer is wrong.

---

src/model/questions/AdditionManyFractions.java
src/model/questions/DerivationPolynomial.java
src/model/questions/IntegrationPolynomial.java
src/model/questions/MathQuestions.java
src/model/questions/MultiplicationManyFractions.java
src/model/questions/TestMathQuestions.java

Also fixed a few things in the fraction classes.

Added derivation and integration of polynomials

---

src/model/Counter.java
src/view/Handlers/ActionHandler.java
src/view/SceneChanger.java

Removed a couple of useless line in Counter, ActionHandler and SceneChanger.

small code cleanup

---

src/controller/GameLogic.java
src/view/HealthBar.java

- Removed some unused variables, getters and setters in the HealthBar class.

Fixed exception after taking initial damage.

---

src/controller/GameLogic.java
src/view/SceneChanger.java

- Fixed a bug where the text colour did not reset when player lost and restarted the game.
- Renamed a method to more accurately describe its purpose.

Fixed visibility bug.

---

src/view/SceneChanger.java

- Fixed a bug where if the player visited the shop then died, game over screen didnt display properly.

Fixed shop bug.

---

src/controller/GameLogic.java

- Made the check answer method shorter. It may still need to become shorter but there is some temporary code in there that will be removed later.

updated check answer

---

src/controller/GameLogic.java
src/model/Player.java
src/model/PlayerList.java
src/view/DifficultiesPanel.java
src/view/Handlers/ActionHandler.java
src/view/MainMenu.java
src/view/ProfilesPanel.java

Difficulties are not synced yet. 
To enter the game:
1. Create a profile
2. Select it
3. Go back
4. Press New Game
5. Press Medium

Difficulties and creating a player

---

resources/backgrounds/sceneTexts.txt
src/view/MainFrame.java
src/view/events/EventShop.java

Font changed from Book Antiqua to Cambria

Changed font to be able to display superscript characters

---

src/controller/ShopItems.java
src/model/Counter.java
src/view/EnemyHealthBar.java
src/view/MainFrame.java
src/view/SceneChanger.java

- Fixed a bug where the gold wouldn't update after the player purchased something from the store.
- Fixed a bug where the shop wouldn't load properly after lvl 15.
- Fixed a bug where a part of the level label got hidden when facing a boss.

shop and level label bugfixes

---

src/view/MainFrame.java

Makes it easier for the user to see the status icons.

Changed position of status icon.

---

src/TEST/TestMathQuestions.java
src/model/questions/Fraction.java
src/model/questions/MQDerivationPolynomial.java
src/model/questions/MQDivisionRemainder2Numbers.java
src/model/questions/MQIntegrationPolynomial.java
src/model/questions/MQQuadraticExpand.java
src/model/questions/MQQuadraticRoots.java
src/model/questions/MQQuadraticSimplify.java
src/model/questions/Polynomial.java
src/model/questions/Quadratic.java
src/model/questions/QuadraticQuestion.java
src/model/questions/Utilities.java

Implemented questions about quadratic expressions.
Fixed string generation for the polynomials.

Quadratic expressions questions

---

resources/entities/enemyLines.txt
src/controller/GameLogic.java
src/view/SceneChanger.java

- Player now gets a unique line after every enemy they defeat.
- Fixed a bug where the name that showed after selecting a profile wasn't correct.

Implemented unique enemy defeat lines

---

src/TEST/TestMathQuestions.java
src/model/questions/MQPolynomialDoubleDerivation.java
src/model/questions/MQPrimeFactorisation.java
src/model/questions/PrimeFactorList.java
src/model/questions/Utilities.java

Prime Factorisation and Double Derivatives

---

src/controller/GameLogic.java

- Fixed a bug where the shield didn't show the correct message after blocking a hit.

Shield bug fix

---

src/TEST/TestMathQuestions.java
src/model/LevelCreator.java
src/model/questions/Arithmetic2NumberQuestions.java
src/model/questions/ArithmeticManyNumbersQuestions.java
src/model/questions/FractionQuestions.java
src/model/questions/MQ2NumbersAddition.java
src/model/questions/MQ2NumbersMultiplication.java
src/model/questions/MQ2NumbersSubtraction.java
src/model/questions/MQDivisionRemainder.java
src/model/questions/MQFinalBossRandom.java
src/model/questions/MQPrimeFactorisation.java
src/model/questions/MQQuadraticRoots.java
src/model/questions/MQQuadraticSimplify.java
src/model/questions/PolynomialCalculusQuestions.java
src/model/questions/QuadraticQuestions.java
src/view/MainFrame.java

Changed every question and the "hint" for each question in the look dialogue.
Also, increased answer button size and changed font.
Uses these guidelines
- Easy: Swedish middle school (högstadie)
- Medium: Swedish high school (gymnasie)
- Hard: Swedish high school (gymnasie) but harder

Adjusting questions for each difficulty

---

src/controller/GameLogic.java
src/model/Timer.java

- Changed the timer label to become red when the clock starts ticking.
- Small change to stop the sound effect from playing when CheckAnswer is called. It solves the issue casuing sound effect spam.

Timer label update

---

resources/saves/highscore.txt
src/controller/GameLogic.java
src/view/HealthBar.java

- Fixed a bug where the damage was not updated before the statement checking if the player was dead executed.

Healthbar bug fixed

---

README.md
src/TEST/TestMathQuestions.java
src/model/questions/Arithmetic2NumberQuestions.java
src/model/questions/ArithmeticManyNumbersQuestions.java
src/model/questions/FractionQuestions.java
src/model/questions/MQDivisionRemainder.java
src/model/questions/MQPrimeFactorisation.java
src/model/questions/MathQuestions.java
src/model/questions/PolynomialCalculusQuestions.java
src/model/questions/QuadraticQuestions.java
src/model/questions/Utilities.java

Changed 1-4 in the answer buttons to A-D
Updated the README file

Answer button and README
